#!/bin/sh 
# Script generated with SVL version 2.3

############
# PROLOGUE #
############
. "${SVL:-$CADP}"/src/svl/standard

SVL_DEBUG=""
SVL_SILENT=""
SVL_IGNORE=""

########
# BODY #
########
SVL_CHECK_FILE \
	"comanche_synch_composition_min.bcg"
SVL_CHECK_FILE \
	"comanche_asynch_composition_min.bcg"
SVL_RECORD_FOR_CLEAN \
	"comanche_synchronizability.bcg"
SVL_COMPARISON \
	"bisimulator" \
	"strong" \
	"bfs" \
	"comanche_synch_composition_min.bcg" \
	"" \
	"comanche_asynch_composition_min.bcg" \
	"" \
	"comanche_synchronizability.bcg" \
	"EQUAL"

############
# EPILOGUE #
############
SVL_PRINT_NEWLINE
SVL_EXIT
